name: merge

on:
  push:
    branches: master
    paths:
      - "merge/*"
      - .github/workflows/merge.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          BASENAME="ghcr.io/flathub/actions"
          IMAGE="${BASENAME}/merge:latest"
          echo ::set-output name=image::${IMAGE}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: merge
          file: merge/Dockerfile
          tags: ${{ steps.prep.outputs.image }}
          push: true
          cache-from: type=registry,ref=${{ steps.prep.outputs.image }}
          cache-to: type=inline
